### ISSUE TITLE
Doesn't work with node

### ISSUE THREAD

**Issue by gregdingle** [mohamedfasil/chi-square-p-value#11]
Nice simple package!

Unfortunately it looks like it doesn't work outside of a web browser because of "umd" mode and lack of `window` object. See https://stackoverflow.com/questions/49111086/webpack-4-universal-library-target and https://github.com/mohamedfasil/chi-square-p-value/blob/master/webpack.config.js#L12 .

**Comment by mohamedfasil** [comment]
I've published the fix onto npm as well @gregdingle
